scan_timeout = 10
command_timeout = 100

right_format = """$time"""

[character]
error_symbol = "[âœ—](bold red)"
success_symbol = "[â¯](bold green)"

[cmd_duration]
min_time = 10
show_milliseconds = true

[directory]
truncation_length = 100
truncate_to_repo = true
truncation_symbol = "â€¦/"

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨â‡¡${count}'
behind = 'ğŸ˜°â‡£${count}'
diverged = 'ğŸ˜µâ‡•â‡¡${ahead_count}â‡£${behind_count}'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'

[sudo]
style = 'bold dimmed green'
symbol = 'ğŸ‘©â€ğŸ’» '
disabled = false

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '+9'
